[package]
name = "conoir_project"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
noir_mpc_ml = { path = "../../" }
fixedpoint = { tag = "v0.1.1", git = "https://github.com/hashcloak/noir-fixed-point" }